### YamlMime:ManagedReference
items:
- uid: CodaParser.Values.MessageOrStructuredMessage
  commentId: T:CodaParser.Values.MessageOrStructuredMessage
  id: MessageOrStructuredMessage
  parent: CodaParser.Values
  children:
  - CodaParser.Values.MessageOrStructuredMessage.#ctor(System.String,CodaParser.Values.TransactionCode)
  - CodaParser.Values.MessageOrStructuredMessage.Message
  - CodaParser.Values.MessageOrStructuredMessage.StructuredMessage
  langs:
  - csharp
  - vb
  name: MessageOrStructuredMessage
  nameWithType: MessageOrStructuredMessage
  fullName: CodaParser.Values.MessageOrStructuredMessage
  type: Class
  source:
    remote:
      path: CodaParser/Values/MessageOrStructuredMessage.cs
      branch: main
      repo: https://github.com/phmatray/coda-parser.git
    id: MessageOrStructuredMessage
    path: ../CodaParser/Values/MessageOrStructuredMessage.cs
    startLine: 2
  assemblies:
  - CodaParser
  namespace: CodaParser.Values
  syntax:
    content: public class MessageOrStructuredMessage
    content.vb: Public Class MessageOrStructuredMessage
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: CodaParser.Values.MessageOrStructuredMessage.#ctor(System.String,CodaParser.Values.TransactionCode)
  commentId: M:CodaParser.Values.MessageOrStructuredMessage.#ctor(System.String,CodaParser.Values.TransactionCode)
  id: '#ctor(System.String,CodaParser.Values.TransactionCode)'
  parent: CodaParser.Values.MessageOrStructuredMessage
  langs:
  - csharp
  - vb
  name: MessageOrStructuredMessage(string, TransactionCode)
  nameWithType: MessageOrStructuredMessage.MessageOrStructuredMessage(string, TransactionCode)
  fullName: CodaParser.Values.MessageOrStructuredMessage.MessageOrStructuredMessage(string, CodaParser.Values.TransactionCode)
  type: Constructor
  source:
    remote:
      path: CodaParser/Values/MessageOrStructuredMessage.cs
      branch: main
      repo: https://github.com/phmatray/coda-parser.git
    id: .ctor
    path: ../CodaParser/Values/MessageOrStructuredMessage.cs
    startLine: 4
  assemblies:
  - CodaParser
  namespace: CodaParser.Values
  syntax:
    content: public MessageOrStructuredMessage(string value, TransactionCode transactionCode)
    parameters:
    - id: value
      type: System.String
    - id: transactionCode
      type: CodaParser.Values.TransactionCode
    content.vb: Public Sub New(value As String, transactionCode As TransactionCode)
  overload: CodaParser.Values.MessageOrStructuredMessage.#ctor*
  nameWithType.vb: MessageOrStructuredMessage.New(String, TransactionCode)
  fullName.vb: CodaParser.Values.MessageOrStructuredMessage.New(String, CodaParser.Values.TransactionCode)
  name.vb: New(String, TransactionCode)
- uid: CodaParser.Values.MessageOrStructuredMessage.Message
  commentId: P:CodaParser.Values.MessageOrStructuredMessage.Message
  id: Message
  parent: CodaParser.Values.MessageOrStructuredMessage
  langs:
  - csharp
  - vb
  name: Message
  nameWithType: MessageOrStructuredMessage.Message
  fullName: CodaParser.Values.MessageOrStructuredMessage.Message
  type: Property
  source:
    remote:
      path: CodaParser/Values/MessageOrStructuredMessage.cs
      branch: main
      repo: https://github.com/phmatray/coda-parser.git
    id: Message
    path: ../CodaParser/Values/MessageOrStructuredMessage.cs
    startLine: 22
  assemblies:
  - CodaParser
  namespace: CodaParser.Values
  syntax:
    content: public Message? Message { get; }
    parameters: []
    return:
      type: CodaParser.Values.Message
    content.vb: Public ReadOnly Property Message As Message
  overload: CodaParser.Values.MessageOrStructuredMessage.Message*
- uid: CodaParser.Values.MessageOrStructuredMessage.StructuredMessage
  commentId: P:CodaParser.Values.MessageOrStructuredMessage.StructuredMessage
  id: StructuredMessage
  parent: CodaParser.Values.MessageOrStructuredMessage
  langs:
  - csharp
  - vb
  name: StructuredMessage
  nameWithType: MessageOrStructuredMessage.StructuredMessage
  fullName: CodaParser.Values.MessageOrStructuredMessage.StructuredMessage
  type: Property
  source:
    remote:
      path: CodaParser/Values/MessageOrStructuredMessage.cs
      branch: main
      repo: https://github.com/phmatray/coda-parser.git
    id: StructuredMessage
    path: ../CodaParser/Values/MessageOrStructuredMessage.cs
    startLine: 24
  assemblies:
  - CodaParser
  namespace: CodaParser.Values
  syntax:
    content: public StructuredMessage? StructuredMessage { get; }
    parameters: []
    return:
      type: CodaParser.Values.StructuredMessage
    content.vb: Public ReadOnly Property StructuredMessage As StructuredMessage
  overload: CodaParser.Values.MessageOrStructuredMessage.StructuredMessage*
references:
- uid: CodaParser.Values
  commentId: N:CodaParser.Values
  href: CodaParser.html
  name: CodaParser.Values
  nameWithType: CodaParser.Values
  fullName: CodaParser.Values
  spec.csharp:
  - uid: CodaParser
    name: CodaParser
    href: CodaParser.html
  - name: .
  - uid: CodaParser.Values
    name: Values
    href: CodaParser.Values.html
  spec.vb:
  - uid: CodaParser
    name: CodaParser
    href: CodaParser.html
  - name: .
  - uid: CodaParser.Values
    name: Values
    href: CodaParser.Values.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: CodaParser.Values.MessageOrStructuredMessage.#ctor*
  commentId: Overload:CodaParser.Values.MessageOrStructuredMessage.#ctor
  href: CodaParser.Values.MessageOrStructuredMessage.html#CodaParser_Values_MessageOrStructuredMessage__ctor_System_String_CodaParser_Values_TransactionCode_
  name: MessageOrStructuredMessage
  nameWithType: MessageOrStructuredMessage.MessageOrStructuredMessage
  fullName: CodaParser.Values.MessageOrStructuredMessage.MessageOrStructuredMessage
  nameWithType.vb: MessageOrStructuredMessage.New
  fullName.vb: CodaParser.Values.MessageOrStructuredMessage.New
  name.vb: New
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: CodaParser.Values.TransactionCode
  commentId: T:CodaParser.Values.TransactionCode
  parent: CodaParser.Values
  href: CodaParser.Values.TransactionCode.html
  name: TransactionCode
  nameWithType: TransactionCode
  fullName: CodaParser.Values.TransactionCode
- uid: CodaParser.Values.MessageOrStructuredMessage.Message*
  commentId: Overload:CodaParser.Values.MessageOrStructuredMessage.Message
  href: CodaParser.Values.MessageOrStructuredMessage.html#CodaParser_Values_MessageOrStructuredMessage_Message
  name: Message
  nameWithType: MessageOrStructuredMessage.Message
  fullName: CodaParser.Values.MessageOrStructuredMessage.Message
- uid: CodaParser.Values.Message
  commentId: T:CodaParser.Values.Message
  parent: CodaParser.Values
  href: CodaParser.Values.Message.html
  name: Message
  nameWithType: Message
  fullName: CodaParser.Values.Message
- uid: CodaParser.Values.MessageOrStructuredMessage.StructuredMessage*
  commentId: Overload:CodaParser.Values.MessageOrStructuredMessage.StructuredMessage
  href: CodaParser.Values.MessageOrStructuredMessage.html#CodaParser_Values_MessageOrStructuredMessage_StructuredMessage
  name: StructuredMessage
  nameWithType: MessageOrStructuredMessage.StructuredMessage
  fullName: CodaParser.Values.MessageOrStructuredMessage.StructuredMessage
- uid: CodaParser.Values.StructuredMessage
  commentId: T:CodaParser.Values.StructuredMessage
  parent: CodaParser.Values
  href: CodaParser.Values.StructuredMessage.html
  name: StructuredMessage
  nameWithType: StructuredMessage
  fullName: CodaParser.Values.StructuredMessage
