### YamlMime:ManagedReference
items:
- uid: CodaParser.Values.StructuredMessage
  commentId: T:CodaParser.Values.StructuredMessage
  id: StructuredMessage
  parent: CodaParser.Values
  children:
  - CodaParser.Values.StructuredMessage.#ctor(System.String,CodaParser.Values.TransactionCode)
  - CodaParser.Values.StructuredMessage.SepaDirectDebit
  - CodaParser.Values.StructuredMessage.StructuredMessageFull
  - CodaParser.Values.StructuredMessage.StructuredMessageType
  - CodaParser.Values.StructuredMessage.Value
  langs:
  - csharp
  - vb
  name: StructuredMessage
  nameWithType: StructuredMessage
  fullName: CodaParser.Values.StructuredMessage
  type: Class
  source:
    remote:
      path: CodaParser/Values/StructuredMessage.cs
      branch: main
      repo: https://github.com/phmatray/coda-parser.git
    id: StructuredMessage
    path: ../CodaParser/Values/StructuredMessage.cs
    startLine: 2
  assemblies:
  - CodaParser
  namespace: CodaParser.Values
  syntax:
    content: public class StructuredMessage
    content.vb: Public Class StructuredMessage
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: CodaParser.Values.StructuredMessage.#ctor(System.String,CodaParser.Values.TransactionCode)
  commentId: M:CodaParser.Values.StructuredMessage.#ctor(System.String,CodaParser.Values.TransactionCode)
  id: '#ctor(System.String,CodaParser.Values.TransactionCode)'
  parent: CodaParser.Values.StructuredMessage
  langs:
  - csharp
  - vb
  name: StructuredMessage(string, TransactionCode)
  nameWithType: StructuredMessage.StructuredMessage(string, TransactionCode)
  fullName: CodaParser.Values.StructuredMessage.StructuredMessage(string, CodaParser.Values.TransactionCode)
  type: Constructor
  source:
    remote:
      path: CodaParser/Values/StructuredMessage.cs
      branch: main
      repo: https://github.com/phmatray/coda-parser.git
    id: .ctor
    path: ../CodaParser/Values/StructuredMessage.cs
    startLine: 4
  assemblies:
  - CodaParser
  namespace: CodaParser.Values
  syntax:
    content: public StructuredMessage(string value, TransactionCode transactionCode)
    parameters:
    - id: value
      type: System.String
    - id: transactionCode
      type: CodaParser.Values.TransactionCode
    content.vb: Public Sub New(value As String, transactionCode As TransactionCode)
  overload: CodaParser.Values.StructuredMessage.#ctor*
  nameWithType.vb: StructuredMessage.New(String, TransactionCode)
  fullName.vb: CodaParser.Values.StructuredMessage.New(String, CodaParser.Values.TransactionCode)
  name.vb: New(String, TransactionCode)
- uid: CodaParser.Values.StructuredMessage.SepaDirectDebit
  commentId: P:CodaParser.Values.StructuredMessage.SepaDirectDebit
  id: SepaDirectDebit
  parent: CodaParser.Values.StructuredMessage
  langs:
  - csharp
  - vb
  name: SepaDirectDebit
  nameWithType: StructuredMessage.SepaDirectDebit
  fullName: CodaParser.Values.StructuredMessage.SepaDirectDebit
  type: Property
  source:
    remote:
      path: CodaParser/Values/StructuredMessage.cs
      branch: main
      repo: https://github.com/phmatray/coda-parser.git
    id: SepaDirectDebit
    path: ../CodaParser/Values/StructuredMessage.cs
    startLine: 25
  assemblies:
  - CodaParser
  namespace: CodaParser.Values
  syntax:
    content: public SepaDirectDebit? SepaDirectDebit { get; }
    parameters: []
    return:
      type: CodaParser.Values.SepaDirectDebit
    content.vb: Public ReadOnly Property SepaDirectDebit As SepaDirectDebit
  overload: CodaParser.Values.StructuredMessage.SepaDirectDebit*
- uid: CodaParser.Values.StructuredMessage.StructuredMessageFull
  commentId: P:CodaParser.Values.StructuredMessage.StructuredMessageFull
  id: StructuredMessageFull
  parent: CodaParser.Values.StructuredMessage
  langs:
  - csharp
  - vb
  name: StructuredMessageFull
  nameWithType: StructuredMessage.StructuredMessageFull
  fullName: CodaParser.Values.StructuredMessage.StructuredMessageFull
  type: Property
  source:
    remote:
      path: CodaParser/Values/StructuredMessage.cs
      branch: main
      repo: https://github.com/phmatray/coda-parser.git
    id: StructuredMessageFull
    path: ../CodaParser/Values/StructuredMessage.cs
    startLine: 27
  assemblies:
  - CodaParser
  namespace: CodaParser.Values
  syntax:
    content: public string StructuredMessageFull { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public ReadOnly Property StructuredMessageFull As String
  overload: CodaParser.Values.StructuredMessage.StructuredMessageFull*
- uid: CodaParser.Values.StructuredMessage.StructuredMessageType
  commentId: P:CodaParser.Values.StructuredMessage.StructuredMessageType
  id: StructuredMessageType
  parent: CodaParser.Values.StructuredMessage
  langs:
  - csharp
  - vb
  name: StructuredMessageType
  nameWithType: StructuredMessage.StructuredMessageType
  fullName: CodaParser.Values.StructuredMessage.StructuredMessageType
  type: Property
  source:
    remote:
      path: CodaParser/Values/StructuredMessage.cs
      branch: main
      repo: https://github.com/phmatray/coda-parser.git
    id: StructuredMessageType
    path: ../CodaParser/Values/StructuredMessage.cs
    startLine: 29
  assemblies:
  - CodaParser
  namespace: CodaParser.Values
  syntax:
    content: public string StructuredMessageType { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public ReadOnly Property StructuredMessageType As String
  overload: CodaParser.Values.StructuredMessage.StructuredMessageType*
- uid: CodaParser.Values.StructuredMessage.Value
  commentId: P:CodaParser.Values.StructuredMessage.Value
  id: Value
  parent: CodaParser.Values.StructuredMessage
  langs:
  - csharp
  - vb
  name: Value
  nameWithType: StructuredMessage.Value
  fullName: CodaParser.Values.StructuredMessage.Value
  type: Property
  source:
    remote:
      path: CodaParser/Values/StructuredMessage.cs
      branch: main
      repo: https://github.com/phmatray/coda-parser.git
    id: Value
    path: ../CodaParser/Values/StructuredMessage.cs
    startLine: 31
  assemblies:
  - CodaParser
  namespace: CodaParser.Values
  syntax:
    content: public string Value { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public ReadOnly Property Value As String
  overload: CodaParser.Values.StructuredMessage.Value*
references:
- uid: CodaParser.Values
  commentId: N:CodaParser.Values
  href: CodaParser.html
  name: CodaParser.Values
  nameWithType: CodaParser.Values
  fullName: CodaParser.Values
  spec.csharp:
  - uid: CodaParser
    name: CodaParser
    href: CodaParser.html
  - name: .
  - uid: CodaParser.Values
    name: Values
    href: CodaParser.Values.html
  spec.vb:
  - uid: CodaParser
    name: CodaParser
    href: CodaParser.html
  - name: .
  - uid: CodaParser.Values
    name: Values
    href: CodaParser.Values.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: CodaParser.Values.StructuredMessage.#ctor*
  commentId: Overload:CodaParser.Values.StructuredMessage.#ctor
  href: CodaParser.Values.StructuredMessage.html#CodaParser_Values_StructuredMessage__ctor_System_String_CodaParser_Values_TransactionCode_
  name: StructuredMessage
  nameWithType: StructuredMessage.StructuredMessage
  fullName: CodaParser.Values.StructuredMessage.StructuredMessage
  nameWithType.vb: StructuredMessage.New
  fullName.vb: CodaParser.Values.StructuredMessage.New
  name.vb: New
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: CodaParser.Values.TransactionCode
  commentId: T:CodaParser.Values.TransactionCode
  parent: CodaParser.Values
  href: CodaParser.Values.TransactionCode.html
  name: TransactionCode
  nameWithType: TransactionCode
  fullName: CodaParser.Values.TransactionCode
- uid: CodaParser.Values.StructuredMessage.SepaDirectDebit*
  commentId: Overload:CodaParser.Values.StructuredMessage.SepaDirectDebit
  href: CodaParser.Values.StructuredMessage.html#CodaParser_Values_StructuredMessage_SepaDirectDebit
  name: SepaDirectDebit
  nameWithType: StructuredMessage.SepaDirectDebit
  fullName: CodaParser.Values.StructuredMessage.SepaDirectDebit
- uid: CodaParser.Values.SepaDirectDebit
  commentId: T:CodaParser.Values.SepaDirectDebit
  parent: CodaParser.Values
  href: CodaParser.Values.SepaDirectDebit.html
  name: SepaDirectDebit
  nameWithType: SepaDirectDebit
  fullName: CodaParser.Values.SepaDirectDebit
- uid: CodaParser.Values.StructuredMessage.StructuredMessageFull*
  commentId: Overload:CodaParser.Values.StructuredMessage.StructuredMessageFull
  href: CodaParser.Values.StructuredMessage.html#CodaParser_Values_StructuredMessage_StructuredMessageFull
  name: StructuredMessageFull
  nameWithType: StructuredMessage.StructuredMessageFull
  fullName: CodaParser.Values.StructuredMessage.StructuredMessageFull
- uid: CodaParser.Values.StructuredMessage.StructuredMessageType*
  commentId: Overload:CodaParser.Values.StructuredMessage.StructuredMessageType
  href: CodaParser.Values.StructuredMessage.html#CodaParser_Values_StructuredMessage_StructuredMessageType
  name: StructuredMessageType
  nameWithType: StructuredMessage.StructuredMessageType
  fullName: CodaParser.Values.StructuredMessage.StructuredMessageType
- uid: CodaParser.Values.StructuredMessage.Value*
  commentId: Overload:CodaParser.Values.StructuredMessage.Value
  href: CodaParser.Values.StructuredMessage.html#CodaParser_Values_StructuredMessage_Value
  name: Value
  nameWithType: StructuredMessage.Value
  fullName: CodaParser.Values.StructuredMessage.Value
